import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'

export const metadata: Metadata = {
  title: 'Perbarui Profile Sekolah | SMA Negeri 2 Lorem',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <ToastContainer />
      {children}
    </>
  )
}
