import type { Metadata } from 'next'
import './globals.css'
import Providers from './provider'
import { Plus_Jakarta_Sans } from 'next/font/google'
import ProgressBar from './progress-bar'

const plus_jakarta_sans = Plus_Jakarta_Sans({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={plus_jakarta_sans.className}>
        <ProgressBar />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
