import type { Metadata } from 'next'
import Sidebar from './components/side-bar'
import Header from './components/header'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { getProfile } from '@/lib/profile'

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const profile = await getProfile()
  return (
    <div className="flex justify-end">
      <Sidebar profile={profile} />
      <main className="bg-[#f4f4f9]  left-[12.666667%] lg:left-[20%] w-[calc(100%-12.666667%)] lg:w-4/5 overflow-y-auto h-full no-scrollbar">
        <Header />
        <ToastContainer className={`z-[10000]`} />
        {children}
      </main>
    </div>
  )
}
