import type { Metadata } from 'next'
import Sidebar from './components/side-bar'
import Header from './components/header'
import { ToastContainer } from 'react-toastify'

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="">
      <Sidebar />
      <main className="bg-[#f4f4f9] fixed left-[12.666667%] lg:left-[20%] w-[calc(100%-12.666667%)] lg:w-4/5 overflow-y-auto h-full no-scrollbar">
        <Header />
        <ToastContainer />
        {children}
      </main>
    </div>
  )
}
