import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Kelola Berita | SMA Negeri 2 Lorem',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <div className="mt-5">{children}</div>
}
