import type { Metadata } from 'next'
import Header from './components/header'
import Footer from './components/footer'
import { getProfile } from '@/lib/profile'

export async function generateMetadata(): Promise<Metadata> {
  const profile = await getProfile()
  return {
    title: `Selamat Data di ${profile.name}`,
    description: 'Generated by create next app',
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const profile = await getProfile()
  return (
    <div>
      <Header profile={profile} />
      {children}
      <div className="h-32"></div>
      <Footer profile={profile} />
    </div>
  )
}
